import { NgFor } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  inject,
  input,
  Input,
  OnInit,
  output,
  Output,
  signal,
} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterOutlet } from '@angular/router';
import { FullNamePipe } from './src/pipes/full-name-pipe';
import { NgForTest } from './src/components/ng-for/ng-for';
import { NgIfTest } from './src/components/ng-if-test/ng-if-test';
import { EventBindingTest } from './src/components/event-binding-test/event-binding-test';
import { PropertyBindingTest } from './src/components/property-binding-test/property-binding-test';
import { TwoWayBindingTest } from './src/components/two-way-binding-test/two-way-binding-test';
import { UnusedImportComponent } from './unused-import.component';
import { AnyTestComponent } from './src/components/any-test/any-test';
import {
  Benchmark0Component,
  Benchmark1Component,
  Benchmark2Component,
  Benchmark3Component,
  Benchmark4Component,
  Benchmark5Component,
  Benchmark6Component,
  Benchmark7Component,
  Benchmark8Component,
  Benchmark9Component,
  Benchmark10Component,
  Benchmark11Component,
  Benchmark12Component,
  Benchmark13Component,
  Benchmark14Component,
  Benchmark15Component,
  Benchmark16Component,
  Benchmark17Component,
  Benchmark18Component,
  Benchmark19Component,
  Benchmark20Component,
  Benchmark21Component,
  Benchmark22Component,
  Benchmark23Component,
  Benchmark24Component,
  Benchmark25Component,
  Benchmark26Component,
  Benchmark27Component,
  Benchmark28Component,
  Benchmark29Component,
  Benchmark30Component,
  Benchmark31Component,
  Benchmark32Component,
  Benchmark33Component,
  Benchmark34Component,
  Benchmark35Component,
  Benchmark36Component,
  Benchmark37Component,
  Benchmark38Component,
  Benchmark39Component,
  Benchmark40Component,
  Benchmark41Component,
  Benchmark42Component,
  Benchmark43Component,
  Benchmark44Component,
  Benchmark45Component,
  Benchmark46Component,
  Benchmark47Component,
  Benchmark48Component,
  Benchmark49Component,
  Benchmark50Component,
  Benchmark51Component,
  Benchmark52Component,
  Benchmark53Component,
  Benchmark54Component,
  Benchmark55Component,
  Benchmark56Component,
  Benchmark57Component,
  Benchmark58Component,
  Benchmark59Component,
  Benchmark60Component,
  Benchmark61Component,
  Benchmark62Component,
  Benchmark63Component,
  Benchmark64Component,
  Benchmark65Component,
  Benchmark66Component,
  Benchmark67Component,
  Benchmark68Component,
  Benchmark69Component,
  Benchmark70Component,
  Benchmark71Component,
  Benchmark72Component,
  Benchmark73Component,
  Benchmark74Component,
  Benchmark75Component,
  Benchmark76Component,
  Benchmark77Component,
  Benchmark78Component,
  Benchmark79Component,
  Benchmark80Component,
  Benchmark81Component,
  Benchmark82Component,
  Benchmark83Component,
  Benchmark84Component,
  Benchmark85Component,
  Benchmark86Component,
  Benchmark87Component,
  Benchmark88Component,
  Benchmark89Component,
  Benchmark90Component,
  Benchmark91Component,
  Benchmark92Component,
  Benchmark93Component,
  Benchmark94Component,
  Benchmark95Component,
  Benchmark96Component,
  Benchmark97Component,
  Benchmark98Component,
  Benchmark99Component,
} from './benchmark';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    NgFor,
    FullNamePipe,
    NgForTest,
    NgIfTest,
    EventBindingTest,
    PropertyBindingTest,
    TwoWayBindingTest,
    UnusedImportComponent,
    AnyTestComponent,
    Benchmark0Component,
    Benchmark1Component,
    Benchmark2Component,
    Benchmark3Component,
    Benchmark4Component,
    Benchmark5Component,
    Benchmark6Component,
    Benchmark7Component,
    Benchmark8Component,
    Benchmark9Component,
    Benchmark10Component,
    Benchmark11Component,
    Benchmark12Component,
    Benchmark13Component,
    Benchmark14Component,
    Benchmark15Component,
    Benchmark16Component,
    Benchmark17Component,
    Benchmark18Component,
    Benchmark19Component,
    Benchmark20Component,
    Benchmark21Component,
    Benchmark22Component,
    Benchmark23Component,
    Benchmark24Component,
    Benchmark25Component,
    Benchmark26Component,
    Benchmark27Component,
    Benchmark28Component,
    Benchmark29Component,
    Benchmark30Component,
    Benchmark31Component,
    Benchmark32Component,
    Benchmark33Component,
    Benchmark34Component,
    Benchmark35Component,
    Benchmark36Component,
    Benchmark37Component,
    Benchmark38Component,
    Benchmark39Component,
    Benchmark40Component,
    Benchmark41Component,
    Benchmark42Component,
    Benchmark43Component,
    Benchmark44Component,
    Benchmark45Component,
    Benchmark46Component,
    Benchmark47Component,
    Benchmark48Component,
    Benchmark49Component,
    Benchmark50Component,
    Benchmark51Component,
    Benchmark52Component,
    Benchmark53Component,
    Benchmark54Component,
    Benchmark55Component,
    Benchmark56Component,
    Benchmark57Component,
    Benchmark58Component,
    Benchmark59Component,
    Benchmark60Component,
    Benchmark61Component,
    Benchmark62Component,
    Benchmark63Component,
    Benchmark64Component,
    Benchmark65Component,
    Benchmark66Component,
    Benchmark67Component,
    Benchmark68Component,
    Benchmark69Component,
    Benchmark70Component,
    Benchmark71Component,
    Benchmark72Component,
    Benchmark73Component,
    Benchmark74Component,
    Benchmark75Component,
    Benchmark76Component,
    Benchmark77Component,
    Benchmark78Component,
    Benchmark79Component,
    Benchmark80Component,
    Benchmark81Component,
    Benchmark82Component,
    Benchmark83Component,
    Benchmark84Component,
    Benchmark85Component,
    Benchmark86Component,
    Benchmark87Component,
    Benchmark88Component,
    Benchmark89Component,
    Benchmark90Component,
    Benchmark91Component,
    Benchmark92Component,
    Benchmark93Component,
    Benchmark94Component,
    Benchmark95Component,
    Benchmark96Component,
    Benchmark97Component,
    Benchmark98Component,
    Benchmark99Component,
  ],
  templateUrl: './app.html',
  styleUrl: './app.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class App implements OnInit {
  @Input() fullName = 'Le Van Trường';

  header = input<string>('header 1');

  header2 = input.required<string>();

  @Output() nameChange = new EventEmitter<string>();

  haderChange = output<string>();

  surname = 'Lê';
  name = 'Trường';

  protected readonly title = signal('demo-app 555 33 3 44 555 222');
  protected readonly items = signal([
    { title: 'Item 9', link: 'https://example.com/item1' },
    { title: 'Item 2', link: 'https://example.com/item2' },
    { title: 'Item 3', link: 'https://example.com/item3' },
  ]);

  protected readonly fb = inject(FormBuilder);

  protected form!: FormGroup;

  ngOnInit(): void {
    this.form = this.fb.group({
      name: ['string', Validators.required],
    });
  }
}
