/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function linkFile(sourceCode: string, filename: string): string;
export interface Diagnostic {
  file?: string;
  message: string;
  code: number;
  start?: number;
  length?: number;
}
export interface CompileOptions {
  hmr?: boolean;
  hmrId?: string;
  rootDir?: string;
}
export interface NapiCompileResult {
  code: string;
  diagnostics: Array<Diagnostic>;
}
export interface FileEntry {
  filename: string;
  content: string;
}
export interface BatchEntryResult {
  filename: string;
  code?: string;
  diagnostics: Array<Diagnostic>;
}
export interface NapiBundleResult {
  bundleJs: string;
  bundleName: string;
  stylesCss?: string;
  scriptsJs?: string;
  polyfillsJs?: string;
  indexHtml?: string;
  files: Record<string, string>;
  rawFiles: Record<string, string>;
  chunks: Record<string, string>;
  chunkNames: Record<string, string>;
  moduleToChunk: Record<string, string>;
  externalImports: Array<string>;
}
export declare class Compiler {
  constructor();
  compile(
    filename: string,
    content: string,
    options?: CompileOptions | undefined | null
  ): NapiCompileResult;
  linkFile(filename: string, sourceCode: string): string;
  compileBatch(files: Array<FileEntry>): Array<BatchEntryResult>;
  getDependencies(entryFile: string): Array<string>;
  bundle(projectPath: string, hmr?: boolean | undefined | null): NapiBundleResult;
  /**
   * Fast pre-scan: returns external package specifiers found in the project's import graph.
   * Uses OXC static analysis only — no Angular compilation — so it's typically ~1-2s.
   * Use this to seed Vite's `optimizeDeps.include` before calling `bundle()` in parallel.
   */
  scanExternalImports(projectPath: string): Array<string>;
}
